### ISSUE TITLE
Chrome replaces Mutify touchbar icon

### ISSUE THREAD

**Issue by strafe** [pixel-point/mutify#2]
It seems a recent Chrome update (I'm running Canary at the moment) has added similar functionality to Mutify, adding a fifth touchbar icon whenever a video is played. I have no idea what this control is for, it seems pretty useless, but it hides the Mutify one.

**Comment by lnikell** [comment]
@strafe In the upcoming release 1.1.2 we added the following functionality that clicks on the mutify in the menu bar or in launchpad restore the icon. 
Since in macOS there only could be one app constantly displayed in the touchbar, some app will override it, but we will support an easy way of restoring it back.

**Comment by lnikell** [comment]
@strafe We released a new version, so you can use check for updates functionality included in the app. In that version, you could click on the icon in the menu bar to reactivate touch bar icon.
